### ISSUE TITLE
atool-test --keep 首页重定向

### ISSUE THREAD

**Issue by jaredleechn** [ant-tool/atool-test#10]
启动 server 的时候，会看到端口的提示，但是 `http://127.0.0.1:9876/tests/runner.html` 这个路径有点长，有几个用户反映找不到在线测试的地址

能不能在 dora 里面配置下 `/` 的重定向，或者跟目录放一个 `index.html` ？

**Comment by silentcloud** [comment]
恩  我搞个迭代支持哈， `http://127.0.0.1:9876` 重定向到 `http://127.0.0.1:9876/tests/runner.html`

**Comment by silentcloud** [comment]
@jaredleechn 搞定， `v0.4.10`
