### ISSUE TITLE
自定义 webpack config 文件名支持

### ISSUE THREAD

**Issue by silentcloud** [ant-tool/atool-test#12]
自定义文件名支持

``` bash
 .option('--config <path>', 'custom config path, default is webpack.config.js')
```

**Comment by jaredleechn** [comment]
感觉和 atool-doc 很多重合的功能，可以相互借鉴下代码，减少重复劳动，https://github.com/ant-tool/atool-doc#command

@ant-tool 另外大家觉得有无必要简化组件开发中 doc 和 test 分开使用的不便？

不是再做一个 spm，而是 doc 和 test 核心模块向后退，不耦合 dora，更核心一些，把 dora 交给 bin 来做，这样各种组件可以自己基于 doc 和 test 封装自己方便的工具

**Comment by silentcloud** [comment]
自定义文件名支持已 ok，issue 先留着讨论 @jaredleechn 的问题

**Comment by jaredleechn** [comment]
如果除去 dora 好像 test 和 doc 就只剩一个 webpackConfig 了，仔细想想不是很好处理，先关掉

不过 doc 和 test 的功能分隔和各自适用场景，以及组件基于二者的最佳实践流程需要梳理清楚下，移步到内网讨论
