### ISSUE TITLE
Try another test tool based on mocha, no phantomjs

### ISSUE THREAD

**Issue by sorrycc** [ant-tool/atool-test#15]
Phantomjs is too large. If only have to test logic, we don't need phantomjs (or electron).

**Comment by silentcloud** [comment]
https://github.com/ant-tool/atool-test/tree/based-jsdom
@sorrycc @jaredleechn @saiyagg @pigcan 

改造之后貌似跟 doc 的定位区分比较明确了，一个用来跑 test 用例，一个用来调试

**Comment by sorrycc** [comment]
新启一个库会不会更合适，感觉两种方式的测试都是需要的，适应不同的场景。

**Comment by silentcloud** [comment]
已新启一个库 [atool-test-mocha](https://github.com/ant-tool/atool-test)
