### ISSUE TITLE
指定测试用例不应入侵到 entry

### ISSUE THREAD

**Issue by jaredleechn** [ant-tool/atool-test#20]
- 如果组件配置了 `webpackConfig.entry = xxx` 会导致在打包的时候，入口文件错误，这个问题还是蛮严重

from @TomHuangCN

**Comment by TomHuangCN** [comment]
＋1

**Comment by silentcloud** [comment]
增加部分测试文件只是在测试用例开发阶段，不应该在最终还保持部分测试用例吧？ @jaredleechn

最终测试编写完毕，应该去除针对测试用例写的 entry

**Comment by jaredleechn** [comment]
这样的话，用户可能要改来改去

@TomHuangCN 你感觉呢？

**Comment by silentcloud** [comment]
那有什么好的建议么？

**Comment by jaredleechn** [comment]
可以用 webpackConfig 上的其它变量来共享这个数据，比如 `webpackConfig.atoolTestSpec` 
或者在 bin 里面的 commander 指定也可以

**Comment by silentcloud** [comment]
@jaredleechn @TomHuangCN  已发布 v0.5.0; `webpackConfig.atoolTestSpec`

**Comment by jaredleechn** [comment]
👍
