### ISSUE TITLE
atool-test phantomjs 问题

### ISSUE THREAD

**Issue by nightink** [ant-tool/atool-test#26]
本地执行 `npm test` 会出现以下错误

![image](https://cloud.githubusercontent.com/assets/2972143/20468533/959e7e56-afd2-11e6-941b-f5f4797add26.png)

并且在 gitlab ci 服务器执行会存在以下错误

![image](https://cloud.githubusercontent.com/assets/2972143/20468566/d4597682-afd2-11e6-8dc4-c10ad04312f8.png)

### 环境信息

使用 npminstall 模式的 npm install

**Comment by silentcloud** [comment]
```
brew install upx
upx -d /path/to/phantomjsbin
```

**Comment by nightink** [comment]
... 服务器 ci 也有问题。。

**Comment by fengmk2** [comment]
@silentcloud 为何不将 phantomjs 升级到最新版本？

**Comment by fengmk2** [comment]
或者改用 electron https://github.com/jprichardson/electron-mocha
