### ISSUE TITLE
采用atool-build webpackConfig

### ISSUE THREAD

**Issue by zinkey** [ant-tool/atool-test#3]
这样 dev，build，test 就是相同基础构建。不至于dev，build可以运行，test不能运行。

**Comment by sorrycc** [comment]
+1

**Comment by sorrycc** [comment]
Karma, mocha, chai, sinon, 是这个组合么?

**Comment by silentcloud** [comment]
已经成功集成 build 的webpack
@sorrycc 断言目前用的expect，如果大家都认同用chai的话，可以改用chai
karma-chai-sinon, karma-sinon-expect 都有插件

听听大家的意见

**Comment by silentcloud** [comment]
采用karma-sinon-chai， chai 支持插件，很爽
