### ISSUE TITLE
peerDependencies.atool-build需升到0.5.x

### ISSUE THREAD

**Issue by sehuo** [ant-tool/atool-test#6]
> npm ERR! peerinvalid The package atool-build@0.5.0 does not satisfy its siblings' peerDependencies requirements!
> npm ERR! peerinvalid Peer atool-test@0.2.9 wants atool-build@~0.4.x

**Comment by sorrycc** [comment]
@silentcloud

**Comment by silentcloud** [comment]
version 0.3.0
