### ISSUE TITLE
tnpm 4 报错

### ISSUE THREAD

**Issue by soda-x** [ant-tool/atool-test#9]
报错信息 

``` bash
sh: /Users/pigcan/Downloads/anima-hd/node_modules/.npminstall/istanbul/0.4.2/.bin/istanbul: No such file or directory

npm ERR! Darwin 15.4.0
```

环境是 `tnpm@4`

问题应该是这边导致的

https://github.com/ant-tool/atool-test/blob/master/src/index.js#L20

**Comment by silentcloud** [comment]
@pigcan 我这边试没出现

**Comment by silentcloud** [comment]
@pigcan 查了，感觉是 tnpm4 的 bug，tnpm4 不能针对非输出bin 目录的模块生成 .bin/命令
![image](https://cloud.githubusercontent.com/assets/1698185/14204006/dcf27c46-f833-11e5-9d47-47ceba201c44.png)

**Comment by silentcloud** [comment]
这是 tnpm3 下面的
![image](https://cloud.githubusercontent.com/assets/1698185/14204105/6e3bdd32-f834-11e5-958d-c042972e19d8.png)

**Comment by silentcloud** [comment]
v0.4.5 fixed
